// <auto-generated />
namespace BugTrackerApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MaxLengthofissueDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaxLengthofissueDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201801280612586_MaxLength of issueDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
